# Generated by Django 5.2.7 on 2025-10-30 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('remaining_seats', models.PositiveIntegerField(default=0)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.year')),
            ],
        ),
    ]
