# Generated by Django 5.2.7 on 2025-10-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
        ('studentside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentside.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminside.subject')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('student', 'priority')},
            },
        ),
    ]
